"""add_ist_time_slot_system_and_demo_clock

Revision ID: 67003a6bff01
Revises: 
Create Date: 2026-08-26 00:45:39.216750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67003a6bff01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_commissions_slot_id'), 'commissions', ['slot_id'], unique=False)
    op.create_index(op.f('ix_purchases_slot_id'), 'purchases', ['slot_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_slot_id'), 'wallet_transactions', ['slot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_slot_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_purchases_slot_id'), table_name='purchases')
    op.drop_index(op.f('ix_commissions_slot_id'), table_name='commissions')
    # ### end Alembic commands ###
